name: polyphony-env
channels:
- conda-forge
dependencies:
- python==3.8
- jupyterlab
- nb_conda>=2.2.1
- pandas>=1.3.0,<1.4
- scikit-learn>=1.0.2,<1.1
- scanpy>=1.8.2,<1.9
- scipy>=1.7.3,<1.8
- tensorflow>=2.0,<=2.5
- umap-learn<=0.5.2
- zarr
- numcodecs
- pip
- pip:
  - scarches>=0.4.0,<0.4.1
  - flask>=1.1.0,<1.2
  - flask-restful>=0.3.8,<0.4.0
  - flask-cors>=3.0,<3.1
  - flasgger==0.9.5
  - pytest
  - pytest-cov>=2.6.0
  - bump2version>=0.5.11
  - wheel
  - watchdog
  - tox
  - traitlets==4.3.3
  - markupsafe==2.0.1
  - twine==1.14.0